<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="ptz_camera" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="mult" value="1" /> <!-- test -->

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="${1*mult*mult*mult}" /> <!-- arbitrary value for mass -->
  <xacro:property name="damping" value="0.7" /> <!-- arbitrary value for mass -->

  <xacro:property name="frame_height_m" value="0.04" /> <!--  -->
  <xacro:property name="frame_radius_m" value="0.07" /> <!--  -->
  <xacro:property name="head_height_m" value="0.02" /> <!--  -->
  <xacro:property name="head_radius_m" value="0.04" /> <!--  -->
  <xacro:property name="eye_radius_m" value="0.035" /> <!--  -->
  <xacro:property name="camera_width_m" value="0.01" /> <!--  -->

  <xacro:property name="frame_height" value="${frame_height_m*mult}" /> <!--  -->
  <xacro:property name="frame_radius" value="${frame_radius_m*mult}" /> <!--  -->
  <xacro:property name="head_height" value="${head_height_m*mult}" /> <!--  -->
  <xacro:property name="head_radius" value="${head_radius_m*mult}" /> <!--  -->
  <xacro:property name="eye_radius" value="${eye_radius_m*mult}" /> <!--  -->
  <xacro:property name="camera_width" value="${camera_width_m*mult}" /> <!--  -->



  <xacro:property name="pan_angle" value="${(1-170/180)*PI}" /> <!-- head to body angle -->
  
  <xacro:property name="tilt_angle" value="${PI*(150/180)}" /> <!-- eye to head angle -->


  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find ptz_camera_description)/urdf/ptz_camera.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find ptz_camera_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="frame"/>
    <origin xyz="0 0 ${frame_height/2.0}" rpy="0 0 0"/>

  </joint>

  <!-- Base Link -->
  <link name="frame">
    <visual>
      <origin xyz="0 0 ${frame_height/2}" rpy="0 0 0"/>
      <geometry>
	<cylinder length="${frame_height}" radius="${frame_radius}"/>
      </geometry>
        <material name="">
          <color rgba="255 0 10 1.0"/>
        </material>
    </visual>

    <collision>
      <origin xyz="0 0 ${frame_height/2}" rpy="0 0 0"/>
      <geometry>
	<cylinder length="${frame_height}" radius="${frame_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${frame_height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (3*frame_radius*frame_radius + frame_height*frame_height)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (3*frame_radius*frame_radius + frame_height*frame_height)}" iyz="0.0"
	  izz="${mass /  2.0 * (frame_radius*frame_radius)}"/>
    </inertial>
  </link>

  <!-- nec -->

  <joint name="nec_joint" type="continuous">
    <parent link="frame"/>
    <child link="head"/>
    <origin xyz="0 ${head_height/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping}"/>
  </joint>

  <!-- head -->

  <link name="head">
    <visual>
      <origin xyz="0 0 ${head_height/2}" rpy="0 0 0"/>
      <geometry>
	<cylinder length="${head_height}" radius="${head_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${head_height/2}" rpy="0 0 0"/>
      <geometry>
	<cylinder length="${head_height}" radius="${head_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${head_height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (3*head_radius*head_radius + head_height*head_height)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (3*head_radius*head_radius + head_height*head_height)}" iyz="0.0"
	  izz="${mass /  2.0 * (head_radius*head_radius)}"/>
    </inertial>
  </link>


<!--eye -->

  <joint name="eye_joint" type="continuous">
    <parent link="head"/>
    <child link="eye"/>
    <origin xyz="0 0 ${eye_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping}"/>
  </joint>

  <link name="eye">
    <visual>
    <origin xyz="0 0 ${eye_radius}" rpy="0 0 0"/>
      <geometry>
	<sphere  radius="${eye_radius}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
    <origin xyz="0 0 ${eye_radius}" rpy="0 0 0"/>
      <geometry>
	<sphere  radius="${eye_radius}"/>
      </geometry>
    </collision>

    <inertial>
    <origin xyz="0 0 ${eye_radius}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass * 2.0 /  5.0 * (eye_radius*eye_radius)}" ixy="0.0" ixz="0.0"
	  iyy="${mass * 2.0 /  5.0 * (eye_radius*eye_radius)}" iyz="0.0"
	  izz="${mass * 2.0 /  5.0 * (eye_radius*eye_radius)}"/>
    </inertial>
  </link>

<!--camera -->

  <joint name="camera_joint" type="fixed">
    <parent link="eye"/>
    <child link="camera"/>
    <origin xyz=" 0 ${camera_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping}"/>
  </joint>

  <link name="camera">
    <visual>
      <origin xyz="0 0 ${camera_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_width} ${camera_width} ${camera_width}"/>
      </geometry>
        <material name="">
            <color rgba="100 100 0 1.0"/>
        </material>
    </visual>


    <collision>
     <origin xyz="0 0 ${camera_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_width} ${camera_width} ${camera_width}"/>
      </geometry>
    </collision>

    <inertial>
     <origin xyz="0 0 ${camera_width/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 6.0 * (camera_width*camera_width)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 6.0 * (camera_width*camera_width)}" iyz="0.0"
	  izz="${mass / 6.0 * (camera_width*camera_width)}"/>
    </inertial>

  </link>


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="nec_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
